name: Mirror to Codeberg

on:
  push:
    branches:
      - "**"  # Trigger on push to any branch
  schedule:
    - cron: '0 0 * * 1'  # Every Monday at 00:00 UTC

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.CODEBERG_SSH }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan codeberg.org >> ~/.ssh/known_hosts

      - name: Add Codeberg as remote
        run: |
          git remote add codeberg git@codeberg.org:driftywinds/mihon-extensions.git
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Push to Codeberg (branches and tags)
        run: |
          git push --prune --force --tags codeberg 'refs/heads/*:refs/heads/*'
